FROM ghcr.io/tom-tan/ldc:1.28.1

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && apt-get install -y --no-install-recommends python3-pip docker-ce-cli && \
    pip install cwltest && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts
