name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      has_tag: ${{ steps.get_info.outputs.has_tag }}
      tag: ${{ steps.get_info.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: get_info
        run: |
          tag="${GITHUB_REF##*/}"
          echo "::set-output name=has_tag::$has_tag"
          echo "::set-output name=tag::$tag"
        env:
          has_tag: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Validate version tag
        if: github.event_name == 'push' && steps.get_info.outputs.has_tag == 'true'
        run: |
          if [ $(cat VERSION) != ${{ steps.get_info.outputs.tag }} ]; then
            echo "::error file=VERSION,line=1,col=1::Version string in VERSION ($(cat VERSION)) does not match the tag string (${{ steps.get_info.outputs.tag }})"
            exit 1
          fi

  test:
    needs: [info]
    strategy:
      matrix:
        dc: [dmd-2.098.1, ldc-latest]
        experimental: [false]
        include:
          - dc: dmd-master
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.dub
          key: ${{ runner.os }}-dub-${{ matrix.dc }}-${{ hashFiles(format('{0}/dub.json', env.GITHUB_WORKSPACE)) }}
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: |
          dub --cache=local test
  
  conformance:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.dub
          key: ${{ runner.os }}-dub-ldc-latest-${{ hashFiles(format('{0}/dub.json', env.GITHUB_WORKSPACE)) }}
      - name: Build alpine dev container
        id: dev_container
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.build
          outputs: type=image,name=shaft-dev
          tags: shaft-dev
      - run: |
          docker run --rm -i -v $GITHUB_WORKSPACE:/workdir -e GITHUB_REF=$GITHUB_REF "shaft-dev" dub --cache=local build -b release-static
          strip bin/shaft
      # - run: |
      #     docker run --rm -i -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE -e GITHUB_REF=$GITHUB_REF alpine:edge ./alpine-build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: shaft-master
          path: ${{ github.workspace }}/bin/shaft
      - name: Run conformance tests
        id: run-conformance
        uses: common-workflow-lab/run-conformance-tests@v1
        with:
          cwlVersion: v1.0
          runner: ${{ github.workspace }}/bin/shaft
          timeout: 30
          tags: command_line_tool,expression_tool
          extra: --remove-tmpdir --veryverbose --enable-compat=extended-props
          n: 1-10
      - name: Save badges
        if: success() && github.event_name == 'push'
        uses: common-workflow-lab/upload-conformance-badges@v1
        with:
          cwlVersion: v1.0
          runner-name: shaft
          badgedir: ${{ steps.run-conformance.outputs.badgedir }}
          repository: ${{ github.repository_owner }}/conformance
          upload-default-branch: true
          ssh-key: ${{ secrets.CONFORMANCE_KEY }}

  release:
    runs-on: ubuntu-latest
    needs: [info, conformance]
    if: github.event_name == 'push' && needs.info.outputs.has_tag == 'true'
    steps:
      - name: Generate release text
        run: |
          cat << EOS > $GITHUB_WORKSPACE/release.md
          ## Conformance tests for CWL ${cwlVersion}
          [![version](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/version.json)](https://github.com/tom-tan/shaft/releases/tag/${tag}) [![commit](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/commit.json)](https://github.com/tom-tan/shaft/tree/${tag})
          ### Classes
          [![CommandLineTool](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/command_line_tool.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html) [![ExpressionTool](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/expression_tool.json?icon=commonwl)](https://www.commonwl.org/v1.0/Workflow.html#ExpressionTool)

          ### Required features
          [![Required](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/required.json?icon=commonwl)](https://www.commonwl.org/v1.0/)

          ### Optional features
          [![DockerRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/docker.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#DockerRequirement) [![EnvVarRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/env_var.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#EnvVarRequirement) [![InitialWorkDirRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/initial_work_dir.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#InitialWorkDirRequirement) [![InlineJavascriptRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/inline_javascript.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#InlineJavascriptRequirement) [![ResourceRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/resource.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#ResourceRequirement) [![SchemaDefRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/schema_def.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#SchemaDefRequirement) [![ShellCommandRequirement](https://badgen.net/https/raw.githubusercontent.com/tom-tan/conformance/master/shaft/cwl_${cwlVersion}/shaft_${tag}/shell_command.json?icon=commonwl)](https://www.commonwl.org/v1.0/CommandLineTool.html#ShellCommandRequirement)
          EOS
        env:
          cwlVersion: v1.0
          tag: ${{ needs.info.outputs.tag }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.info.outputs.tag }}
          release_name: ${{ needs.info.outputs.tag }}
          body_path: ${{ github.workspace }}/release.md
      - uses: actions/download-artifact@v3
        with:
          name: shaft-master
      - run: |
          chmod +x shaft
          tar cf ${GITHUB_WORKSPACE}/shaft.tar.gz shaft
      - name: Upload shaft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/shaft.tar.gz
          asset_name: shaft-linux-x86_64.tar.gz
          asset_content_type: application/tar+gzip
