name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        dc: [dmd-2.098.1, ldc-latest]
        experimental: [false]
        include:
          - dc: dmd-master
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ matrix.dc }}-${{ hashFiles('**/dub.json') }}
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: |
          dub test
  
  conformance:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-ldc-latest-${{ hashFiles('**/dub.json') }}
      - run: |
          apk --no-cache add dub ldc gcc musl-dev git llvm-libunwind-static bash docker-cli
          dub build -b release-static
          strip bin/shaft
      - uses: actions/upload-artifact@v2
        with:
          name: shaft-master
          path: ${{ github.workspace }}/bin/
      - name: Run conformance tests
        id: run-conformance
        uses: common-workflow-lab/run-conformance-tests@v1
        with:
          cwlVersion: v1.0
          runner: ${{ github.workspace }}/bin/shaft
          timeout: 30
          tags: command_line_tool,expression_tool
